package MyBank;

/**
* MyBank/AccountDetailsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* Saturday, April 7, 2012 1:30:10 PM CEST
*/

public final class AccountDetailsHolder implements org.omg.CORBA.portable.Streamable
{
  public MyBank.AccountDetails value = null;

  public AccountDetailsHolder ()
  {
  }

  public AccountDetailsHolder (MyBank.AccountDetails initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MyBank.AccountDetailsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MyBank.AccountDetailsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MyBank.AccountDetailsHelper.type ();
  }

}
