package MyBank;


/**
* MyBank/AccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* Saturday, April 7, 2012 1:30:10 PM CEST
*/

public interface AccountOperations 
{
  void deposit (double amount);
  void withdraw (double amount) throws MyBank.InsufficientFunds;
  MyBank.AccountDetails details ();
} // interface AccountOperations
