package MyBank;

/**
* MyBank/AccountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* Saturday, April 7, 2012 1:30:10 PM CEST
*/

public final class AccountHolder implements org.omg.CORBA.portable.Streamable
{
  public MyBank.Account value = null;

  public AccountHolder ()
  {
  }

  public AccountHolder (MyBank.Account initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MyBank.AccountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MyBank.AccountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MyBank.AccountHelper.type ();
  }

}
