package MyBank;

/**
* MyBank/BankHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Bank.idl
* Saturday, April 7, 2012 1:30:10 PM CEST
*/

public final class BankHolder implements org.omg.CORBA.portable.Streamable
{
  public MyBank.Bank value = null;

  public BankHolder ()
  {
  }

  public BankHolder (MyBank.Bank initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MyBank.BankHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MyBank.BankHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MyBank.BankHelper.type ();
  }

}
