package chat;


/**
* chat/ChatServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Friday, April 6, 2012 6:43:18 PM CEST
*/

public interface ChatServer extends ChatServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ChatServer
