package chat;


/**
* chat/ChatClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Friday, April 6, 2012 6:43:18 PM CEST
*/

public interface ChatClientOperations 
{
  void printMsg (String msg);
} // interface ChatClientOperations
