package TimeZone;


/**
* TimeZone/Interface_TimeZone.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from TimeZone.idl
* jeudi 22 août 2002 19 h 31 CEST
*/

public interface Interface_TimeZone extends Interface_TimeZoneOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Interface_TimeZone
