package TimeZone;


/**
* TimeZone/Interface_TimeZoneHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from TimeZone.idl
* jeudi 22 août 2002 19 h 31 CEST
*/

abstract public class Interface_TimeZoneHelper
{
  private static String  _id = "IDL:TimeZone/Interface_TimeZone:1.0";

  public static void insert (org.omg.CORBA.Any a, TimeZone.Interface_TimeZone that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static TimeZone.Interface_TimeZone extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (TimeZone.Interface_TimeZoneHelper.id (), "Interface_TimeZone");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static TimeZone.Interface_TimeZone read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_Interface_TimeZoneStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, TimeZone.Interface_TimeZone value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static TimeZone.Interface_TimeZone narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof TimeZone.Interface_TimeZone)
      return (TimeZone.Interface_TimeZone)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      TimeZone._Interface_TimeZoneStub stub = new TimeZone._Interface_TimeZoneStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
