package TimeZone;


/**
* TimeZone/Interface_TimeZoneOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from TimeZone.idl
* jeudi 22 août 2002 19 h 31 CEST
*/

public interface Interface_TimeZoneOperations 
{
  String get_date ();
  String get_help ();
  String get_ids ();
  String get_time ();
  String set_timezone (String timezone);
} // interface Interface_TimeZoneOperations
