package TimeZone;

/**
* TimeZone/Interface_TimeZoneHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from TimeZone.idl
* jeudi 22 août 2002 19 h 31 CEST
*/

public final class Interface_TimeZoneHolder implements org.omg.CORBA.portable.Streamable
{
  public TimeZone.Interface_TimeZone value = null;

  public Interface_TimeZoneHolder ()
  {
  }

  public Interface_TimeZoneHolder (TimeZone.Interface_TimeZone initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = TimeZone.Interface_TimeZoneHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    TimeZone.Interface_TimeZoneHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return TimeZone.Interface_TimeZoneHelper.type ();
  }

}
