package _DoodlePackage;


/**
* _DoodlePackage/DoodleDetailsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* Saturday, April 14, 2012 4:19:04 PM CEST
*/

abstract public class DoodleDetailsHelper
{
  private static String  _id = "IDL:DoodlePackage/DoodleDetails:1.0";

  public static void insert (org.omg.CORBA.Any a, _DoodlePackage.DoodleDetails that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static _DoodlePackage.DoodleDetails extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = _DoodlePackage.DoodleParticipantHelper.type ();
          _members0[0] = new org.omg.CORBA.StructMember (
            "creatorDoodle",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "nameDoodle",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "scheduleDoodle",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (_DoodlePackage.DoodleDetailsHelper.id (), "DoodleDetails", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static _DoodlePackage.DoodleDetails read (org.omg.CORBA.portable.InputStream istream)
  {
    _DoodlePackage.DoodleDetails value = new _DoodlePackage.DoodleDetails ();
    value.creatorDoodle = _DoodlePackage.DoodleParticipantHelper.read (istream);
    value.nameDoodle = istream.read_string ();
    value.scheduleDoodle = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, _DoodlePackage.DoodleDetails value)
  {
    _DoodlePackage.DoodleParticipantHelper.write (ostream, value.creatorDoodle);
    ostream.write_string (value.nameDoodle);
    ostream.write_string (value.scheduleDoodle);
  }

}
