package _DoodlePackage;


/**
* _DoodlePackage/DoodleInformerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* Saturday, April 14, 2012 4:19:04 PM CEST
*/


//----------------------------------------------
public interface DoodleInformerOperations 
{
  void informParticipants (_DoodlePackage.Doodle doodle, String finalDayHour);
  void addClient (_DoodlePackage.DoodleParticipant client);
  void fwdMsg (String msg);
} // interface DoodleInformerOperations
