package _DoodlePackage;

/**
* _DoodlePackage/DoodleParticipantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* Saturday, April 14, 2012 4:19:04 PM CEST
*/


//----------------------------------------------
public final class DoodleParticipantHolder implements org.omg.CORBA.portable.Streamable
{
  public _DoodlePackage.DoodleParticipant value = null;

  public DoodleParticipantHolder ()
  {
  }

  public DoodleParticipantHolder (_DoodlePackage.DoodleParticipant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = _DoodlePackage.DoodleParticipantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    _DoodlePackage.DoodleParticipantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return _DoodlePackage.DoodleParticipantHelper.type ();
  }

}
