package _DoodlePackage;

/**
* _DoodlePackage/DoodleHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* Saturday, April 14, 2012 4:19:04 PM CEST
*/


//----------------------------------------------
public final class DoodleHolder implements org.omg.CORBA.portable.Streamable
{
  public _DoodlePackage.Doodle value = null;

  public DoodleHolder ()
  {
  }

  public DoodleHolder (_DoodlePackage.Doodle initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = _DoodlePackage.DoodleHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    _DoodlePackage.DoodleHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return _DoodlePackage.DoodleHelper.type ();
  }

}
