package _DoodlePackage;


/**
* _DoodlePackage/DoodlePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* Saturday, April 14, 2012 4:19:04 PM CEST
*/


//----------------------------------------------
public abstract class DoodlePOA extends org.omg.PortableServer.Servant
 implements _DoodlePackage.DoodleOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("containsParticipant", new java.lang.Integer (0));
    _methods.put ("addParticipant", new java.lang.Integer (1));
    _methods.put ("addDayHour", new java.lang.Integer (2));
    _methods.put ("_get_details", new java.lang.Integer (3));
    _methods.put ("getParticipants", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // _DoodlePackage/Doodle/containsParticipant
       {
         _DoodlePackage.DoodleParticipant client = _DoodlePackage.DoodleParticipantHelper.read (in);
         boolean $result = false;
         $result = this.containsParticipant (client);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // _DoodlePackage/Doodle/addParticipant
       {
         _DoodlePackage.DoodleParticipant participant = _DoodlePackage.DoodleParticipantHelper.read (in);
         this.addParticipant (participant);
         out = $rh.createReply();
         break;
       }

       case 2:  // _DoodlePackage/Doodle/addDayHour
       {
         String dayhour = in.read_string ();
         this.addDayHour (dayhour);
         out = $rh.createReply();
         break;
       }

       case 3:  // _DoodlePackage/Doodle/_get_details
       {
         _DoodlePackage.DoodleDetails $result = null;
         $result = this.details ();
         out = $rh.createReply();
         _DoodlePackage.DoodleDetailsHelper.write (out, $result);
         break;
       }

       case 4:  // _DoodlePackage/Doodle/getParticipants
       {
         _DoodlePackage.DoodleParticipant $result[] = null;
         $result = this.getParticipants ();
         out = $rh.createReply();
         _DoodlePackage.ParticipantsHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DoodlePackage/Doodle:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Doodle _this() 
  {
    return DoodleHelper.narrow(
    super._this_object());
  }

  public Doodle _this(org.omg.CORBA.ORB orb) 
  {
    return DoodleHelper.narrow(
    super._this_object(orb));
  }


} // class DoodlePOA
