package _DoodlePackage;


/**
* _DoodlePackage/DoodleDetails.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* Saturday, April 14, 2012 4:19:04 PM CEST
*/

public final class DoodleDetails implements org.omg.CORBA.portable.IDLEntity
{
  public _DoodlePackage.DoodleParticipant creatorDoodle = null;
  public String nameDoodle = null;
  public String scheduleDoodle = null;

  public DoodleDetails ()
  {
  } // ctor

  public DoodleDetails (_DoodlePackage.DoodleParticipant _creatorDoodle, String _nameDoodle, String _scheduleDoodle)
  {
    creatorDoodle = _creatorDoodle;
    nameDoodle = _nameDoodle;
    scheduleDoodle = _scheduleDoodle;
  } // ctor

} // class DoodleDetails
