package _DoodlePackage;


/**
* _DoodlePackage/DoodleParticipantPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* Saturday, April 14, 2012 4:19:04 PM CEST
*/


//----------------------------------------------
public abstract class DoodleParticipantPOA extends org.omg.PortableServer.Servant
 implements _DoodlePackage.DoodleParticipantOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("printMsg", new java.lang.Integer (0));
    _methods.put ("startRunning", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // _DoodlePackage/DoodleParticipant/printMsg
       {
         String msg = _DoodlePackage.MessageHelper.read (in);
         this.printMsg (msg);
         out = $rh.createReply();
         break;
       }

       case 1:  // _DoodlePackage/DoodleParticipant/startRunning
       {
         this.startRunning ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DoodlePackage/DoodleParticipant:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DoodleParticipant _this() 
  {
    return DoodleParticipantHelper.narrow(
    super._this_object());
  }

  public DoodleParticipant _this(org.omg.CORBA.ORB orb) 
  {
    return DoodleParticipantHelper.narrow(
    super._this_object(orb));
  }


} // class DoodleParticipantPOA
