package _DoodlePackage;


/**
* _DoodlePackage/DoodleParticipantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* Saturday, April 14, 2012 4:19:04 PM CEST
*/


//----------------------------------------------
public interface DoodleParticipantOperations 
{
  void printMsg (String msg);
  void startRunning ();
} // interface DoodleParticipantOperations
