package _DoodlePackage;

/**
* _DoodlePackage/DoodleInformerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* Saturday, April 14, 2012 4:19:04 PM CEST
*/


//----------------------------------------------
public final class DoodleInformerHolder implements org.omg.CORBA.portable.Streamable
{
  public _DoodlePackage.DoodleInformer value = null;

  public DoodleInformerHolder ()
  {
  }

  public DoodleInformerHolder (_DoodlePackage.DoodleInformer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = _DoodlePackage.DoodleInformerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    _DoodlePackage.DoodleInformerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return _DoodlePackage.DoodleInformerHelper.type ();
  }

}
