package _DoodlePackage;

/**
* _DoodlePackage/ManageDoodleHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* Saturday, April 14, 2012 4:19:04 PM CEST
*/


//----------------------------------------------
public final class ManageDoodleHolder implements org.omg.CORBA.portable.Streamable
{
  public _DoodlePackage.ManageDoodle value = null;

  public ManageDoodleHolder ()
  {
  }

  public ManageDoodleHolder (_DoodlePackage.ManageDoodle initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = _DoodlePackage.ManageDoodleHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    _DoodlePackage.ManageDoodleHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return _DoodlePackage.ManageDoodleHelper.type ();
  }

}
