package _DoodlePackage;


/**
* _DoodlePackage/ManageDoodleOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* Saturday, April 14, 2012 4:19:04 PM CEST
*/


//----------------------------------------------
public interface ManageDoodleOperations 
{
  _DoodlePackage.Doodle createDoodle (String nameDoodle, _DoodlePackage.DoodleParticipant creatorDoodle);
  void voteDoodle (_DoodlePackage.Doodle doodle, String dayhour, _DoodlePackage.DoodleParticipant participant);
  _DoodlePackage.Doodle getDoodle (String nameDoodle);
  _DoodlePackage.Doodle closeDoodle (_DoodlePackage.Doodle doodle, String finalDayHour, _DoodlePackage.DoodleParticipant creatorDoodle);
} // interface ManageDoodleOperations
