package _DoodlePackage;


/**
* _DoodlePackage/ManageDoodle.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* Saturday, April 14, 2012 4:19:04 PM CEST
*/


//----------------------------------------------
public interface ManageDoodle extends ManageDoodleOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ManageDoodle
