package My_Math;


/**
* My_Math/Interface_MathPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Math.idl
* jeudi 22 août 2002 19 h 49 CEST
*/

public abstract class Interface_MathPOA extends org.omg.PortableServer.Servant
 implements My_Math.Interface_MathOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addition", new java.lang.Integer (0));
    _methods.put ("get_help", new java.lang.Integer (1));
    _methods.put ("multiplication", new java.lang.Integer (2));
    _methods.put ("subtraction", new java.lang.Integer (3));
    _methods.put ("transpose", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // My_Math/Interface_Math/addition
       {
         My_Math.My_Array a = My_Math.My_ArrayHelper.read (in);
         int line_a = in.read_long ();
         int row_a = in.read_long ();
         My_Math.My_Array b = My_Math.My_ArrayHelper.read (in);
         int line_b = in.read_long ();
         int row_b = in.read_long ();
         My_Math.Result $result = null;
         $result = this.addition (a, line_a, row_a, b, line_b, row_b);
         out = $rh.createReply();
         My_Math.ResultHelper.write (out, $result);
         break;
       }


  //
       case 1:  // My_Math/Interface_Math/get_help
       {
         String $result = null;
         $result = this.get_help ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  //
       case 2:  // My_Math/Interface_Math/multiplication
       {
         My_Math.My_Array a = My_Math.My_ArrayHelper.read (in);
         int line_a = in.read_long ();
         int row_a = in.read_long ();
         My_Math.My_Array b = My_Math.My_ArrayHelper.read (in);
         int line_b = in.read_long ();
         int row_b = in.read_long ();
         My_Math.Result $result = null;
         $result = this.multiplication (a, line_a, row_a, b, line_b, row_b);
         out = $rh.createReply();
         My_Math.ResultHelper.write (out, $result);
         break;
       }


  //
       case 3:  // My_Math/Interface_Math/subtraction
       {
         My_Math.My_Array a = My_Math.My_ArrayHelper.read (in);
         int line_a = in.read_long ();
         int row_a = in.read_long ();
         My_Math.My_Array b = My_Math.My_ArrayHelper.read (in);
         int line_b = in.read_long ();
         int row_b = in.read_long ();
         My_Math.Result $result = null;
         $result = this.subtraction (a, line_a, row_a, b, line_b, row_b);
         out = $rh.createReply();
         My_Math.ResultHelper.write (out, $result);
         break;
       }


  //
       case 4:  // My_Math/Interface_Math/transpose
       {
         My_Math.My_Array a = My_Math.My_ArrayHelper.read (in);
         int line_a = in.read_long ();
         int row_a = in.read_long ();
         My_Math.Result $result = null;
         $result = this.transpose (a, line_a, row_a);
         out = $rh.createReply();
         My_Math.ResultHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:My_Math/Interface_Math:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Interface_Math _this() 
  {
    return Interface_MathHelper.narrow(
    super._this_object());
  }

  public Interface_Math _this(org.omg.CORBA.ORB orb) 
  {
    return Interface_MathHelper.narrow(
    super._this_object(orb));
  }


} // class Interface_MathPOA
