package My_Math;


/**
* My_Math/Interface_MathOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Math.idl
* jeudi 22 août 2002 19 h 49 CEST
*/

public interface Interface_MathOperations 
{
  My_Math.Result addition (My_Math.My_Array a, int line_a, int row_a, My_Math.My_Array b, int line_b, int row_b);

  //
  String get_help ();

  //
  My_Math.Result multiplication (My_Math.My_Array a, int line_a, int row_a, My_Math.My_Array b, int line_b, int row_b);

  //
  My_Math.Result subtraction (My_Math.My_Array a, int line_a, int row_a, My_Math.My_Array b, int line_b, int row_b);

  //
  My_Math.Result transpose (My_Math.My_Array a, int line_a, int row_a);
} // interface Interface_MathOperations
