package My_Math;

/**
* My_Math/Interface_MathHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Math.idl
* jeudi 22 août 2002 19 h 49 CEST
*/

public final class Interface_MathHolder implements org.omg.CORBA.portable.Streamable
{
  public My_Math.Interface_Math value = null;

  public Interface_MathHolder ()
  {
  }

  public Interface_MathHolder (My_Math.Interface_Math initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = My_Math.Interface_MathHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    My_Math.Interface_MathHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return My_Math.Interface_MathHelper.type ();
  }

}
