package My_Math;

/**
* My_Math/My_ArrayHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Math.idl
* jeudi 22 août 2002 19 h 49 CEST
*/

public final class My_ArrayHolder implements org.omg.CORBA.portable.Streamable
{
  public My_Math.My_Array value = null;

  public My_ArrayHolder ()
  {
  }

  public My_ArrayHolder (My_Math.My_Array initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = My_Math.My_ArrayHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    My_Math.My_ArrayHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return My_Math.My_ArrayHelper.type ();
  }

}
