package My_Math;


/**
* My_Math/My_Array.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Math.idl
* jeudi 22 août 2002 19 h 49 CEST
*/

public final class My_Array implements org.omg.CORBA.portable.IDLEntity
{
  public float bi_array[][] = null;

  public My_Array ()
  {
  } // ctor

  public My_Array (float[][] _bi_array)
  {
    bi_array = _bi_array;
  } // ctor

} // class My_Array
