package My_Math;

/**
* My_Math/ResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Math.idl
* jeudi 22 août 2002 19 h 49 CEST
*/

public final class ResultHolder implements org.omg.CORBA.portable.Streamable
{
  public My_Math.Result value = null;

  public ResultHolder ()
  {
  }

  public ResultHolder (My_Math.Result initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = My_Math.ResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    My_Math.ResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return My_Math.ResultHelper.type ();
  }

}
