package My_Math;


/**
* My_Math/SIZE_MAX.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Math.idl
* jeudi 22 août 2002 19 h 49 CEST
*/

public interface SIZE_MAX
{
  public static final int value = (int)(100);
}
