//
// Generated file, do not edit! Created by opp_msgc 4.1 from internetMsg.msg.
//

#ifndef _INTERNETMSG_M_H_
#define _INTERNETMSG_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>internetMsg.msg</tt> by opp_msgc.
 * <pre>
 * message InternetMsg
 * {
 *     int source;  
 *     int destination;  
 *     string content;
 *     int msgType;  
 *     string topic;
 *     unsigned long seqNumber;
 *     double timestamp;   
 *     int connectedBrokers[];
 *     double connectedBrokersTimeStamp[];
 *     double globaltime;
 *     double agreedlocaltime;
 *     double clockdriftrate;
 * }
 * </pre>
 */
class InternetMsg : public ::cMessage
{
  protected:
    int source_var;
    int destination_var;
    opp_string content_var;
    int msgType_var;
    opp_string topic_var;
    unsigned long seqNumber_var;
    double timestamp_var;
    int *connectedBrokers_var; // array ptr
    unsigned int connectedBrokers_arraysize;
    double *connectedBrokersTimeStamp_var; // array ptr
    unsigned int connectedBrokersTimeStamp_arraysize;
    double globaltime_var;
    double agreedlocaltime_var;
    double clockdriftrate_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const InternetMsg&);

  public:
    InternetMsg(const char *name=NULL, int kind=0);
    InternetMsg(const InternetMsg& other);
    virtual ~InternetMsg();
    InternetMsg& operator=(const InternetMsg& other);
    virtual InternetMsg *dup() const {return new InternetMsg(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source_var);
    virtual int getDestination() const;
    virtual void setDestination(int destination_var);
    virtual const char * getContent() const;
    virtual void setContent(const char * content_var);
    virtual int getMsgType() const;
    virtual void setMsgType(int msgType_var);
    virtual const char * getTopic() const;
    virtual void setTopic(const char * topic_var);
    virtual unsigned long getSeqNumber() const;
    virtual void setSeqNumber(unsigned long seqNumber_var);
    virtual double getTimestamp() const;
    virtual void setTimestamp(double timestamp_var);
    virtual void setConnectedBrokersArraySize(unsigned int size);
    virtual unsigned int getConnectedBrokersArraySize() const;
    virtual int getConnectedBrokers(unsigned int k) const;
    virtual void setConnectedBrokers(unsigned int k, int connectedBrokers_var);
    virtual void setConnectedBrokersTimeStampArraySize(unsigned int size);
    virtual unsigned int getConnectedBrokersTimeStampArraySize() const;
    virtual double getConnectedBrokersTimeStamp(unsigned int k) const;
    virtual void setConnectedBrokersTimeStamp(unsigned int k, double connectedBrokersTimeStamp_var);
    virtual double getGlobaltime() const;
    virtual void setGlobaltime(double globaltime_var);
    virtual double getAgreedlocaltime() const;
    virtual void setAgreedlocaltime(double agreedlocaltime_var);
    virtual double getClockdriftrate() const;
    virtual void setClockdriftrate(double clockdriftrate_var);
};

inline void doPacking(cCommBuffer *b, InternetMsg& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, InternetMsg& obj) {obj.parsimUnpack(b);}


#endif // _INTERNETMSG_M_H_
