package Finance;

/**
* Finance/AccountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Account.idl
* Saturday, April 7, 2012 1:27:11 PM CEST
*/

public final class AccountHolder implements org.omg.CORBA.portable.Streamable
{
  public Finance.Account value = null;

  public AccountHolder ()
  {
  }

  public AccountHolder (Finance.Account initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Finance.AccountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Finance.AccountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Finance.AccountHelper.type ();
  }

}
