package Finance;


/**
* Finance/AccountOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Account.idl
* Saturday, April 7, 2012 1:27:11 PM CEST
*/

public interface AccountOperations 
{
  void deposit (double amount);
  void withdraw (double amount) throws Finance.InsufficientFunds;
  Finance.AccountDetails details ();
} // interface AccountOperations
