package Finance;


/**
* Finance/AccountPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Account.idl
* Saturday, April 7, 2012 1:27:11 PM CEST
*/

public abstract class AccountPOA extends org.omg.PortableServer.Servant
 implements Finance.AccountOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("deposit", new java.lang.Integer (0));
    _methods.put ("withdraw", new java.lang.Integer (1));
    _methods.put ("_get_details", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Finance/Account/deposit
       {
         double amount = in.read_double ();
         this.deposit (amount);
         out = $rh.createReply();
         break;
       }

       case 1:  // Finance/Account/withdraw
       {
         try {
           double amount = in.read_double ();
           this.withdraw (amount);
           out = $rh.createReply();
         } catch (Finance.InsufficientFunds $ex) {
           out = $rh.createExceptionReply ();
           Finance.InsufficientFundsHelper.write (out, $ex);
         }
         break;
       }

       case 2:  // Finance/Account/_get_details
       {
         Finance.AccountDetails $result = null;
         $result = this.details ();
         out = $rh.createReply();
         Finance.AccountDetailsHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Finance/Account:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Account _this() 
  {
    return AccountHelper.narrow(
    super._this_object());
  }

  public Account _this(org.omg.CORBA.ORB orb) 
  {
    return AccountHelper.narrow(
    super._this_object(orb));
  }


} // class AccountPOA
