package Finance;


/**
* Finance/AccountHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Account.idl
* Saturday, April 7, 2012 1:27:11 PM CEST
*/

abstract public class AccountHelper
{
  private static String  _id = "IDL:Finance/Account:1.0";

  public static void insert (org.omg.CORBA.Any a, Finance.Account that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Finance.Account extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Finance.AccountHelper.id (), "Account");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Finance.Account read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AccountStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Finance.Account value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Finance.Account narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Finance.Account)
      return (Finance.Account)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Finance._AccountStub stub = new Finance._AccountStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Finance.Account unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Finance.Account)
      return (Finance.Account)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Finance._AccountStub stub = new Finance._AccountStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
