package Finance;


/**
* Finance/InsufficientFunds.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Account.idl
* Saturday, April 7, 2012 1:27:11 PM CEST
*/

public final class InsufficientFunds extends org.omg.CORBA.UserException
{

  public InsufficientFunds ()
  {
    super(InsufficientFundsHelper.id());
  } // ctor


  public InsufficientFunds (String $reason)
  {
    super(InsufficientFundsHelper.id() + "  " + $reason);
  } // ctor

} // class InsufficientFunds
