package Persistent;


/**
* Persistent/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PersistentHello.idl
* Thursday, April 5, 2012 1:14:03 PM CEST
*/


//HelloApp
public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
