package Persistent;


/**
* Persistent/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PersistentHello.idl
* Thursday, April 5, 2012 1:14:03 PM CEST
*/


//HelloApp
public interface HelloOperations 
{
  String sayHello ();
  void shutdown ();
} // interface HelloOperations
