package Persistent;

/**
* Persistent/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PersistentHello.idl
* Thursday, April 5, 2012 1:14:03 PM CEST
*/


//HelloApp
public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public Persistent.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (Persistent.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = Persistent.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    Persistent.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return Persistent.HelloHelper.type ();
  }

}
