package Persistent;


/**
* Persistent/HelloHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PersistentHello.idl
* Thursday, April 5, 2012 1:14:03 PM CEST
*/


//HelloApp
abstract public class HelloHelper
{
  private static String  _id = "IDL:Persistent/Hello:1.0";

  public static void insert (org.omg.CORBA.Any a, Persistent.Hello that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static Persistent.Hello extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (Persistent.HelloHelper.id (), "Hello");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static Persistent.Hello read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_HelloStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, Persistent.Hello value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static Persistent.Hello narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Persistent.Hello)
      return (Persistent.Hello)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Persistent._HelloStub stub = new Persistent._HelloStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static Persistent.Hello unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof Persistent.Hello)
      return (Persistent.Hello)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      Persistent._HelloStub stub = new Persistent._HelloStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
