package _DoodlePackage;

/**
* _DoodlePackage/DoodleDetailsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* Saturday, April 14, 2012 4:19:04 PM CEST
*/

public final class DoodleDetailsHolder implements org.omg.CORBA.portable.Streamable
{
  public _DoodlePackage.DoodleDetails value = null;

  public DoodleDetailsHolder ()
  {
  }

  public DoodleDetailsHolder (_DoodlePackage.DoodleDetails initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = _DoodlePackage.DoodleDetailsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    _DoodlePackage.DoodleDetailsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return _DoodlePackage.DoodleDetailsHelper.type ();
  }

}
