package _DoodlePackage;


/**
* _DoodlePackage/DoodleOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* Saturday, April 14, 2012 4:19:04 PM CEST
*/


//----------------------------------------------
public interface DoodleOperations 
{
  boolean containsParticipant (_DoodlePackage.DoodleParticipant client);
  void addParticipant (_DoodlePackage.DoodleParticipant participant);
  void addDayHour (String dayhour);
  _DoodlePackage.DoodleDetails details ();
  _DoodlePackage.DoodleParticipant[] getParticipants ();
} // interface DoodleOperations
