package _DoodlePackage;


/**
* _DoodlePackage/ParticipantsHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* Saturday, April 14, 2012 4:19:04 PM CEST
*/


//----------------------------------------------
abstract public class ParticipantsHelper
{
  private static String  _id = "IDL:DoodlePackage/Participants:1.0";

  public static void insert (org.omg.CORBA.Any a, _DoodlePackage.DoodleParticipant[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static _DoodlePackage.DoodleParticipant[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = _DoodlePackage.DoodleParticipantHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (_DoodlePackage.ParticipantsHelper.id (), "Participants", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static _DoodlePackage.DoodleParticipant[] read (org.omg.CORBA.portable.InputStream istream)
  {
    _DoodlePackage.DoodleParticipant value[] = null;
    int _len0 = istream.read_long ();
    value = new _DoodlePackage.DoodleParticipant[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = _DoodlePackage.DoodleParticipantHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, _DoodlePackage.DoodleParticipant[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      _DoodlePackage.DoodleParticipantHelper.write (ostream, value[_i0]);
  }

}
