package _DoodlePackage;


/**
* _DoodlePackage/ParticipantsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Doodle.idl
* Saturday, April 14, 2012 4:19:04 PM CEST
*/


//----------------------------------------------
public final class ParticipantsHolder implements org.omg.CORBA.portable.Streamable
{
  public _DoodlePackage.DoodleParticipant value[] = null;

  public ParticipantsHolder ()
  {
  }

  public ParticipantsHolder (_DoodlePackage.DoodleParticipant[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = _DoodlePackage.ParticipantsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    _DoodlePackage.ParticipantsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return _DoodlePackage.ParticipantsHelper.type ();
  }

}
