package HelloWorld;


/**
* HelloWorld/Interface_Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Hello.idl
* jeudi 22 août 2002 19 h 06 CEST
*/

public interface Interface_Hello extends Interface_HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Interface_Hello
