package HelloWorld;

/**
* HelloWorld/Interface_HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Hello.idl
* jeudi 22 août 2002 19 h 06 CEST
*/

public final class Interface_HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloWorld.Interface_Hello value = null;

  public Interface_HelloHolder ()
  {
  }

  public Interface_HelloHolder (HelloWorld.Interface_Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloWorld.Interface_HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloWorld.Interface_HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloWorld.Interface_HelloHelper.type ();
  }

}
