package HelloWorld;


/**
* HelloWorld/Interface_HelloHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Hello.idl
* jeudi 22 août 2002 19 h 06 CEST
*/

abstract public class Interface_HelloHelper
{
  private static String  _id = "IDL:HelloWorld/Interface_Hello:1.0";

  public static void insert (org.omg.CORBA.Any a, HelloWorld.Interface_Hello that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static HelloWorld.Interface_Hello extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (HelloWorld.Interface_HelloHelper.id (), "Interface_Hello");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static HelloWorld.Interface_Hello read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_Interface_HelloStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, HelloWorld.Interface_Hello value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static HelloWorld.Interface_Hello narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof HelloWorld.Interface_Hello)
      return (HelloWorld.Interface_Hello)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      HelloWorld._Interface_HelloStub stub = new HelloWorld._Interface_HelloStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
