package HelloWorld;


/**
* HelloWorld/Interface_HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from Hello.idl
* jeudi 22 août 2002 19 h 06 CEST
*/

public interface Interface_HelloOperations 
{
  String get_msg ();
} // interface Interface_HelloOperations
