//
// Generated file, do not edit! Created by opp_msgc 4.1 from internetPacket.msg.
//

#ifndef _INTERNETPACKET_M_H_
#define _INTERNETPACKET_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>internetPacket.msg</tt> by opp_msgc.
 * <pre>
 * enum DSP2_INTERNET_PACKET_TYPES{
 * 	DSP2_INTERNET_DATA_PACKET = 0;
 * 	DSP2_INTERNET_NACK_PACKET = 1;
 * };
 * </pre>
 */
enum DSP2_INTERNET_PACKET_TYPES {
    DSP2_INTERNET_DATA_PACKET = 0,
    DSP2_INTERNET_NACK_PACKET = 1
};

/**
 * Class generated from <tt>internetPacket.msg</tt> by opp_msgc.
 * <pre>
 * packet InternetPacket {
 *     int pktType @enum(DSP2_INTERNET_PACKET_TYPES);
 *     int srcAddress;
 *     int destAddress;
 *     unsigned long seqNumber;
 *     unsigned long ackSeqNumber;
 * }
 * </pre>
 */
class InternetPacket : public ::cPacket
{
  protected:
    int pktType_var;
    int srcAddress_var;
    int destAddress_var;
    unsigned long seqNumber_var;
    unsigned long ackSeqNumber_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const InternetPacket&);

  public:
    InternetPacket(const char *name=NULL, int kind=0);
    InternetPacket(const InternetPacket& other);
    virtual ~InternetPacket();
    InternetPacket& operator=(const InternetPacket& other);
    virtual InternetPacket *dup() const {return new InternetPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getPktType() const;
    virtual void setPktType(int pktType_var);
    virtual int getSrcAddress() const;
    virtual void setSrcAddress(int srcAddress_var);
    virtual int getDestAddress() const;
    virtual void setDestAddress(int destAddress_var);
    virtual unsigned long getSeqNumber() const;
    virtual void setSeqNumber(unsigned long seqNumber_var);
    virtual unsigned long getAckSeqNumber() const;
    virtual void setAckSeqNumber(unsigned long ackSeqNumber_var);
};

inline void doPacking(cCommBuffer *b, InternetPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, InternetPacket& obj) {obj.parsimUnpack(b);}


#endif // _INTERNETPACKET_M_H_
